
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minijava;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\002\004\000\002\002\004\000\002\012" +
    "\004\000\002\012\002\000\002\003\023\000\002\004\010" +
    "\000\002\004\012\000\002\013\004\000\002\013\002\000" +
    "\002\005\005\000\002\014\004\000\002\014\002\000\002" +
    "\006\017\000\002\015\003\000\002\015\002\000\002\016" +
    "\004\000\002\016\006\000\002\007\005\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\017\004\000" +
    "\002\017\002\000\002\010\005\000\002\010\011\000\002" +
    "\010\007\000\002\010\007\000\002\010\006\000\002\010" +
    "\011\000\002\011\005\000\002\011\005\000\002\011\005" +
    "\000\002\011\005\000\002\011\005\000\002\011\006\000" +
    "\002\011\005\000\002\011\010\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\007\000\002\011\006\000\002\011\004" +
    "\000\002\011\005\000\002\020\003\000\002\020\002\000" +
    "\002\021\003\000\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\004\006\001\002\000\004\002\216\001" +
    "\002\000\006\002\ufffe\004\141\001\002\000\004\027\007" +
    "\001\002\000\004\047\010\001\002\000\004\005\011\001" +
    "\002\000\004\006\012\001\002\000\004\007\013\001\002" +
    "\000\004\010\014\001\002\000\004\045\015\001\002\000" +
    "\004\015\016\001\002\000\004\043\017\001\002\000\004" +
    "\044\020\001\002\000\004\027\021\001\002\000\004\046" +
    "\022\001\002\000\004\047\023\001\002\000\014\016\031" +
    "\020\030\026\026\027\024\047\025\001\002\000\006\037" +
    "\130\043\127\001\002\000\016\016\031\020\030\026\026" +
    "\027\024\047\025\050\uffeb\001\002\000\004\045\117\001" +
    "\002\000\004\050\115\001\002\000\004\045\111\001\002" +
    "\000\004\045\032\001\002\000\022\021\035\022\037\023" +
    "\041\024\033\027\040\030\034\036\042\045\043\001\002" +
    "\000\006\013\103\027\102\001\002\000\030\031\uffdc\032" +
    "\uffdc\033\uffdc\034\uffdc\035\uffdc\040\uffdc\041\uffdc\042\uffdc" +
    "\043\uffdc\044\uffdc\046\uffdc\001\002\000\030\031\uffdb\032" +
    "\uffdb\033\uffdb\034\uffdb\035\uffdb\040\uffdb\041\uffdb\042\uffdb" +
    "\043\uffdb\044\uffdb\046\uffdb\001\002\000\022\031\047\032" +
    "\052\033\050\034\051\035\045\042\054\043\053\046\076" +
    "\001\002\000\030\031\uffda\032\uffda\033\uffda\034\uffda\035" +
    "\uffda\040\uffda\041\uffda\042\uffda\043\uffda\044\uffda\046\uffda" +
    "\001\002\000\030\031\uffd9\032\uffd9\033\uffd9\034\uffd9\035" +
    "\uffd9\040\uffd9\041\uffd9\042\uffd9\043\uffd9\044\uffd9\046\uffd9" +
    "\001\002\000\030\031\uffd8\032\uffd8\033\uffd8\034\uffd8\035" +
    "\uffd8\040\uffd8\041\uffd8\042\uffd8\043\uffd8\044\uffd8\046\uffd8" +
    "\001\002\000\022\021\035\022\037\023\041\024\033\027" +
    "\040\030\034\036\042\045\043\001\002\000\022\021\035" +
    "\022\037\023\041\024\033\027\040\030\034\036\042\045" +
    "\043\001\002\000\022\031\047\032\052\033\050\034\051" +
    "\035\045\042\054\043\053\046\046\001\002\000\022\021" +
    "\035\022\037\023\041\024\033\027\040\030\034\036\042" +
    "\045\043\001\002\000\030\031\uffd4\032\uffd4\033\uffd4\034" +
    "\uffd4\035\uffd4\040\uffd4\041\uffd4\042\uffd4\043\uffd4\044\uffd4" +
    "\046\uffd4\001\002\000\022\021\035\022\037\023\041\024" +
    "\033\027\040\030\034\036\042\045\043\001\002\000\022" +
    "\021\035\022\037\023\041\024\033\027\040\030\034\036" +
    "\042\045\043\001\002\000\022\021\035\022\037\023\041" +
    "\024\033\027\040\030\034\036\042\045\043\001\002\000" +
    "\022\021\035\022\037\023\041\024\033\027\040\030\034" +
    "\036\042\045\043\001\002\000\022\021\035\022\037\023" +
    "\041\024\033\027\040\030\034\036\042\045\043\001\002" +
    "\000\006\025\056\027\055\001\002\000\004\045\057\001" +
    "\002\000\030\031\uffde\032\uffde\033\uffde\034\uffde\035\uffde" +
    "\040\uffde\041\uffde\042\uffde\043\uffde\044\uffde\046\uffde\001" +
    "\002\000\024\021\035\022\037\023\041\024\033\027\040" +
    "\030\034\036\042\045\043\046\uffd2\001\002\000\006\041" +
    "\064\046\uffd3\001\002\000\024\031\047\032\052\033\050" +
    "\034\051\035\045\041\uffd1\042\054\043\053\046\uffd1\001" +
    "\002\000\004\046\063\001\002\000\030\031\uffdd\032\uffdd" +
    "\033\uffdd\034\uffdd\035\uffdd\040\uffdd\041\uffdd\042\uffdd\043" +
    "\uffdd\044\uffdd\046\uffdd\001\002\000\022\021\035\022\037" +
    "\023\041\024\033\027\040\030\034\036\042\045\043\001" +
    "\002\000\024\031\047\032\052\033\050\034\051\035\045" +
    "\041\uffd0\042\054\043\053\046\uffd0\001\002\000\022\031" +
    "\047\032\052\033\050\034\051\035\045\042\054\043\053" +
    "\044\067\001\002\000\030\031\uffdf\032\uffdf\033\uffdf\034" +
    "\uffdf\035\uffdf\040\uffdf\041\uffdf\042\uffdf\043\uffdf\044\uffdf" +
    "\046\uffdf\001\002\000\030\031\uffe3\032\uffe3\033\050\034" +
    "\051\035\045\040\uffe3\041\uffe3\042\uffe3\043\uffe3\044\uffe3" +
    "\046\uffe3\001\002\000\030\031\uffe1\032\uffe1\033\uffe1\034" +
    "\uffe1\035\045\040\uffe1\041\uffe1\042\uffe1\043\uffe1\044\uffe1" +
    "\046\uffe1\001\002\000\030\031\uffe2\032\uffe2\033\uffe2\034" +
    "\uffe2\035\045\040\uffe2\041\uffe2\042\uffe2\043\uffe2\044\uffe2" +
    "\046\uffe2\001\002\000\030\031\uffe4\032\052\033\050\034" +
    "\051\035\045\040\uffe4\041\uffe4\042\uffe4\043\uffe4\044\uffe4" +
    "\046\uffe4\001\002\000\030\031\uffe0\032\uffe0\033\uffe0\034" +
    "\uffe0\035\uffe0\040\uffe0\041\uffe0\042\uffe0\043\uffe0\044\uffe0" +
    "\046\uffe0\001\002\000\030\031\uffd5\032\uffd5\033\uffd5\034" +
    "\uffd5\035\uffd5\040\uffd5\041\uffd5\042\uffd5\043\uffd5\044\uffd5" +
    "\046\uffd5\001\002\000\014\016\031\020\030\026\026\027" +
    "\024\047\025\001\002\000\004\017\100\001\002\000\014" +
    "\016\031\020\030\026\026\027\024\047\025\001\002\000" +
    "\022\012\uffe9\016\uffe9\017\uffe9\020\uffe9\026\uffe9\027\uffe9" +
    "\047\uffe9\050\uffe9\001\002\000\004\045\107\001\002\000" +
    "\004\043\104\001\002\000\022\021\035\022\037\023\041" +
    "\024\033\027\040\030\034\036\042\045\043\001\002\000" +
    "\022\031\047\032\052\033\050\034\051\035\045\042\054" +
    "\043\053\044\106\001\002\000\030\031\uffd7\032\uffd7\033" +
    "\uffd7\034\uffd7\035\uffd7\040\uffd7\041\uffd7\042\uffd7\043\uffd7" +
    "\044\uffd7\046\uffd7\001\002\000\004\046\110\001\002\000" +
    "\030\031\uffd6\032\uffd6\033\uffd6\034\uffd6\035\uffd6\040\uffd6" +
    "\041\uffd6\042\uffd6\043\uffd6\044\uffd6\046\uffd6\001\002\000" +
    "\022\021\035\022\037\023\041\024\033\027\040\030\034" +
    "\036\042\045\043\001\002\000\022\031\047\032\052\033" +
    "\050\034\051\035\045\042\054\043\053\046\113\001\002" +
    "\000\014\016\031\020\030\026\026\027\024\047\025\001" +
    "\002\000\022\012\uffe8\016\uffe8\017\uffe8\020\uffe8\026\uffe8" +
    "\027\uffe8\047\uffe8\050\uffe8\001\002\000\004\050\116\001" +
    "\002\000\006\002\ufffd\004\ufffd\001\002\000\022\021\035" +
    "\022\037\023\041\024\033\027\040\030\034\036\042\045" +
    "\043\001\002\000\022\031\047\032\052\033\050\034\051" +
    "\035\045\042\054\043\053\046\121\001\002\000\004\040" +
    "\122\001\002\000\022\012\uffe7\016\uffe7\017\uffe7\020\uffe7" +
    "\026\uffe7\027\uffe7\047\uffe7\050\uffe7\001\002\000\020\012" +
    "\uffeb\016\031\020\030\026\026\027\024\047\025\050\uffeb" +
    "\001\002\000\004\050\125\001\002\000\022\012\uffea\016" +
    "\uffea\017\uffea\020\uffea\026\uffea\027\uffea\047\uffea\050\uffea" +
    "\001\002\000\006\012\uffec\050\uffec\001\002\000\022\021" +
    "\035\022\037\023\041\024\033\027\040\030\034\036\042" +
    "\045\043\001\002\000\022\021\035\022\037\023\041\024" +
    "\033\027\040\030\034\036\042\045\043\001\002\000\022" +
    "\031\047\032\052\033\050\034\051\035\045\040\132\042" +
    "\054\043\053\001\002\000\022\012\uffe6\016\uffe6\017\uffe6" +
    "\020\uffe6\026\uffe6\027\uffe6\047\uffe6\050\uffe6\001\002\000" +
    "\022\031\047\032\052\033\050\034\051\035\045\042\054" +
    "\043\053\044\134\001\002\000\004\037\135\001\002\000" +
    "\022\021\035\022\037\023\041\024\033\027\040\030\034" +
    "\036\042\045\043\001\002\000\022\031\047\032\052\033" +
    "\050\034\051\035\045\040\137\042\054\043\053\001\002" +
    "\000\022\012\uffe5\016\uffe5\017\uffe5\020\uffe5\026\uffe5\027" +
    "\uffe5\047\uffe5\050\uffe5\001\002\000\006\002\ufffe\004\141" +
    "\001\002\000\004\027\143\001\002\000\004\002\001\001" +
    "\002\000\006\011\145\047\144\001\002\000\014\005\ufff9" +
    "\013\155\014\154\027\150\050\ufff9\001\002\000\004\027" +
    "\146\001\002\000\004\047\147\001\002\000\014\005\ufff9" +
    "\013\155\014\154\027\150\050\ufff9\001\002\000\004\027" +
    "\uffed\001\002\000\004\027\210\001\002\000\006\005\163" +
    "\050\ufff6\001\002\000\026\005\ufff9\012\ufff9\013\155\014" +
    "\154\016\ufff9\020\ufff9\026\ufff9\027\150\047\ufff9\050\ufff9" +
    "\001\002\000\004\027\uffef\001\002\000\006\027\uffee\043" +
    "\156\001\002\000\004\044\157\001\002\000\004\027\ufff0" +
    "\001\002\000\022\005\ufffa\012\ufffa\016\ufffa\020\ufffa\026" +
    "\ufffa\027\ufffa\047\ufffa\050\ufffa\001\002\000\004\050\207" +
    "\001\002\000\006\005\163\050\ufff6\001\002\000\010\013" +
    "\155\014\154\027\150\001\002\000\004\027\165\001\002" +
    "\000\004\045\166\001\002\000\012\013\155\014\154\027" +
    "\150\046\ufff3\001\002\000\006\041\203\046\ufff4\001\002" +
    "\000\004\027\202\001\002\000\004\046\172\001\002\000" +
    "\004\047\173\001\002\000\022\012\ufff9\013\155\014\154" +
    "\016\ufff9\020\ufff9\026\ufff9\027\150\047\ufff9\001\002\000" +
    "\016\012\uffeb\016\031\020\030\026\026\027\024\047\025" +
    "\001\002\000\004\012\176\001\002\000\022\021\035\022" +
    "\037\023\041\024\033\027\040\030\034\036\042\045\043" +
    "\001\002\000\022\031\047\032\052\033\050\034\051\035" +
    "\045\040\200\042\054\043\053\001\002\000\004\050\201" +
    "\001\002\000\006\005\ufff5\050\ufff5\001\002\000\006\041" +
    "\ufff2\046\ufff2\001\002\000\010\013\155\014\154\027\150" +
    "\001\002\000\004\027\205\001\002\000\006\041\ufff1\046" +
    "\ufff1\001\002\000\004\050\ufff7\001\002\000\006\002\ufffb" +
    "\004\ufffb\001\002\000\004\040\211\001\002\000\026\005" +
    "\ufff8\012\ufff8\013\ufff8\014\ufff8\016\ufff8\020\ufff8\026\ufff8" +
    "\027\ufff8\047\ufff8\050\ufff8\001\002\000\006\005\163\050" +
    "\ufff6\001\002\000\004\050\214\001\002\000\006\002\ufffc" +
    "\004\ufffc\001\002\000\004\002\uffff\001\002\000\004\002" +
    "\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\137\012\141\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\026" +
    "\001\001\000\002\001\001\000\006\010\122\017\123\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\074\001\001\000\004\011\043\001\001\000\002" +
    "\001\001\000\004\011\073\001\001\000\002\001\001\000" +
    "\004\011\072\001\001\000\004\011\071\001\001\000\004" +
    "\011\070\001\001\000\004\011\067\001\001\000\004\011" +
    "\065\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\060\020\061\021\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\064\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\076\001\001\000\002" +
    "\001\001\000\004\010\100\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\104\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\111\001\001\000\002\001\001" +
    "\000\004\010\113\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\117\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\010" +
    "\122\017\125\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\132\001\001\000\004\011" +
    "\130\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\135\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\137\012\214" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\005\152\007\150\013\211\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\005\152\007\150\013" +
    "\151\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\161\014\160\001\001\000\010\005\152\007\150\013" +
    "\157\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\006\161\014\205\001\001\000\004\007\163" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\167\015\170\016\166\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\005" +
    "\152\007\150\013\173\001\001\000\006\010\122\017\174" +
    "\001\001\000\002\001\001\000\004\011\176\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\203\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\161\014\212\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Erro de Sintaxe");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {
                m.append(" na linha "+(s.left+1));
                if (s.right >= 0)
                    m.append(", coluna "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Goal ::= MainClass ClassDeclarationList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Goal",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Goal EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ClassDeclarationList ::= ClassDeclaration ClassDeclarationList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ClassDeclarationList",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ClassDeclarationList ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ClassDeclarationList",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // MainClass ::= CLASS ID LBRACE PUBLIC STATIC VOID MAIN LPAREN STRING_TYPE LBRACK RBRACK ID RPAREN LBRACE Statement RBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("MainClass",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // ClassDeclaration ::= CLASS ID LBRACE VarDeclarationList MethodDeclarationList RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ClassDeclaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ClassDeclaration ::= CLASS ID EXTENDS ID LBRACE VarDeclarationList MethodDeclarationList RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ClassDeclaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // VarDeclarationList ::= VarDeclaration VarDeclarationList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VarDeclarationList",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // VarDeclarationList ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VarDeclarationList",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VarDeclaration ::= Type ID SEMICOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VarDeclaration",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // MethodDeclarationList ::= MethodDeclaration MethodDeclarationList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("MethodDeclarationList",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // MethodDeclarationList ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("MethodDeclarationList",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // MethodDeclaration ::= PUBLIC Type ID LPAREN OptFormalList RPAREN LBRACE VarDeclarationList StatementList RETURN Expression SEMICOL RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("MethodDeclaration",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // OptFormalList ::= FormalList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OptFormalList",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // OptFormalList ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OptFormalList",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // FormalList ::= Type ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FormalList",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // FormalList ::= FormalList COMMA Type ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FormalList",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= INT LBRACK RBRACK 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Type ::= INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Type ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // StatementList ::= Statement StatementList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StatementList",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // StatementList ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StatementList",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Statement ::= LBRACE StatementList RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Statement ::= IF LPAREN Expression RPAREN Statement ELSE Statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Statement ::= WHILE LPAREN Expression RPAREN Statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Statement ::= PRINT LPAREN Expression RPAREN SEMICOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Statement ::= ID ASSIGN Expression SEMICOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Statement ::= ID LBRACK Expression RBRACK ASSIGN Expression SEMICOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Expression ::= Expression AND Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Expression ::= Expression LESSTHAN Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Expression ::= Expression PLUS Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Expression ::= Expression MINUS Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Expression ::= Expression MULT Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Expression ::= Expression LBRACK Expression RBRACK 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Expression ::= Expression DOT LENGTH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Expression ::= Expression DOT ID LPAREN OptExpressionList RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Expression ::= NUMBER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Expression ::= TRUE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Expression ::= FALSE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Expression ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Expression ::= THIS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Expression ::= NEW INT LBRACK Expression RBRACK 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Expression ::= NEW ID LPAREN RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Expression ::= NOT Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Expression ::= LPAREN Expression RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // OptExpressionList ::= ExpressionList 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OptExpressionList",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // OptExpressionList ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OptExpressionList",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // ExpressionList ::= Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpressionList",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ExpressionList ::= ExpressionList COMMA Expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpressionList",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
