
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minijava;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 27;
  public static final int LPAREN = 35;
  public static final int INT = 9;
  public static final int MINUS = 26;
  public static final int RPAREN = 36;
  public static final int STATIC = 4;
  public static final int NOT = 28;
  public static final int AND = 23;
  public static final int LESSTHAN = 24;
  public static final int COMMA = 31;
  public static final int SEMICOL = 30;
  public static final int CLASS = 2;
  public static final int PLUS = 25;
  public static final int ASSIGN = 29;
  public static final int MAIN = 6;
  public static final int IF = 12;
  public static final int THIS = 17;
  public static final int DOT = 32;
  public static final int ID = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 10;
  public static final int RETURN = 8;
  public static final int STRING_TYPE = 11;
  public static final int TRUE = 15;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int NUMBER = 22;
  public static final int VOID = 5;
  public static final int LBRACK = 33;
  public static final int LBRACE = 37;
  public static final int ELSE = 13;
  public static final int RBRACK = 34;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int RBRACE = 38;
  public static final int EXTENDS = 7;
  public static final int FALSE = 16;
  public static final int PRINT = 20;
  public static final int LENGTH = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "EXTENDS",
  "RETURN",
  "INT",
  "BOOLEAN",
  "STRING_TYPE",
  "IF",
  "ELSE",
  "WHILE",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "LENGTH",
  "PRINT",
  "ID",
  "NUMBER",
  "AND",
  "LESSTHAN",
  "PLUS",
  "MINUS",
  "MULT",
  "NOT",
  "ASSIGN",
  "SEMICOL",
  "COMMA",
  "DOT",
  "LBRACK",
  "RBRACK",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE"
  };
}

